INSERT INTO customer (c_id,name,address) VALUES (1,'Fitzgerald Brown','Ap #491-1781 Lacus. Avenue');
INSERT INTO customer (c_id,name,address) VALUES (2,'Nissim Lawson','Ap #842-3536 Dolor Road');
INSERT INTO customer (c_id,name,address) VALUES (3,'Drew Dodson','3336 Sed St.');
INSERT INTO customer (c_id,name,address) VALUES (4,'Samuel Santana','Ap #150-3675 A, Rd.');
INSERT INTO customer (c_id,name,address) VALUES (5,'Harrison Leonard','Ap #617-4357 Vitae Rd.');
INSERT INTO customer (c_id,name,address) VALUES (6,'Lance Lindsay','834-7935 Et, Road');
INSERT INTO customer (c_id,name,address) VALUES (7,'Brett Rojas','P.O. Box 843, 9606 Libero Street');
INSERT INTO customer (c_id,name,address) VALUES (8,'Dylan Mcknight','Ap #370-9204 Gravida Av.');
INSERT INTO customer (c_id,name,address) VALUES (9,'Lucius Riley','Ap #426-4315 Metus St.');
INSERT INTO customer (c_id,name,address) VALUES (10,'Linus Santos','4846 Mauris St.');
INSERT INTO customer (c_id,name,address) VALUES (11,'Tobias Marshall','P.O. Box 147, 2910 Mauris. Ave');
INSERT INTO customer (c_id,name,address) VALUES (12,'Kasper Lopez','P.O. Box 894, 3113 Egestas Avenue');
INSERT INTO customer (c_id,name,address) VALUES (13,'Tucker Chen','Ap #450-5777 Cras Ave');
INSERT INTO customer (c_id,name,address) VALUES (14,'Bruno Jefferson','956-2391 Nascetur St.');
INSERT INTO customer (c_id,name,address) VALUES (15,'Reed Eaton','9595 Phasellus Rd.');
INSERT INTO customer (c_id,name,address) VALUES (16,'Gareth Fitzpatrick','471-5222 Tincidunt Rd.');
INSERT INTO customer (c_id,name,address) VALUES (17,'Damon Carey','P.O. Box 135, 8631 Aliquet, Rd.');
INSERT INTO customer (c_id,name,address) VALUES (18,'Jared Weeks','P.O. Box 164, 3320 Nibh. Ave');
INSERT INTO customer (c_id,name,address) VALUES (19,'Lane Palmer','5459 Donec Avenue');
INSERT INTO customer (c_id,name,address) VALUES (20,'Yasir Reeves','739-1517 Aliquam Street');
INSERT INTO customer (c_id,name,address) VALUES (21,'Christian Bradshaw','170-453 Maecenas Road');
INSERT INTO customer (c_id,name,address) VALUES (22,'Lester Lowery','739-9809 Nunc Ave');
INSERT INTO customer (c_id,name,address) VALUES (23,'Nigel Nicholson','Ap #798-1252 Et, Ave');
INSERT INTO customer (c_id,name,address) VALUES (24,'Kennedy Jacobs','Ap #282-4986 Est Road');
INSERT INTO customer (c_id,name,address) VALUES (25,'Fulton Bentley','P.O. Box 463, 6070 Tristique Av.');
INSERT INTO customer (c_id,name,address) VALUES (26,'Rudyard Ford','750-8769 Aliquet St.');
INSERT INTO customer (c_id,name,address) VALUES (27,'Reece Hendricks','4585 Ultrices Ave');
INSERT INTO customer (c_id,name,address) VALUES (28,'Chase Burnett','6386 Fringilla Rd.');
INSERT INTO customer (c_id,name,address) VALUES (29,'Mason Cherry','835-3804 Nec Rd.');
INSERT INTO customer (c_id,name,address) VALUES (30,'Alec Strickland','872-6444 Quisque Avenue');
INSERT INTO customer (c_id,name,address) VALUES (31,'Vance Tyler','P.O. Box 758, 7144 Nunc, St.');
INSERT INTO customer (c_id,name,address) VALUES (32,'Curran Robles','381-7175 Ipsum Av.');
INSERT INTO customer (c_id,name,address) VALUES (33,'Lev Miller','8162 Sit Rd.');
INSERT INTO customer (c_id,name,address) VALUES (34,'Robert Snyder','P.O. Box 309, 2192 Cras Street');
INSERT INTO customer (c_id,name,address) VALUES (35,'Derek Holden','1566 Lacus, Rd.');
INSERT INTO customer (c_id,name,address) VALUES (36,'Hayden Atkinson','435-4119 Dis Ave');
INSERT INTO customer (c_id,name,address) VALUES (37,'Dylan Foley','P.O. Box 770, 7001 Donec Av.');
INSERT INTO customer (c_id,name,address) VALUES (38,'Austin Kinney','7489 Sodales St.');
INSERT INTO customer (c_id,name,address) VALUES (39,'Alden Hoffman','140-1283 Nullam Street');
INSERT INTO customer (c_id,name,address) VALUES (40,'Brett Peck','P.O. Box 180, 6290 Tristique Street');
INSERT INTO customer (c_id,name,address) VALUES (41,'Nero Deleon','P.O. Box 802, 9604 Curae; St.');
INSERT INTO customer (c_id,name,address) VALUES (42,'Ryder Beard','664-8922 Maecenas Av.');
INSERT INTO customer (c_id,name,address) VALUES (43,'Ishmael Hurley','5382 Donec Avenue');
INSERT INTO customer (c_id,name,address) VALUES (44,'Carson Tyson','P.O. Box 595, 2246 Pellentesque Road');
INSERT INTO customer (c_id,name,address) VALUES (45,'Salvador Nelson','326-1170 Nunc St.');
INSERT INTO customer (c_id,name,address) VALUES (46,'Hedley Smith','Ap #957-7603 Consectetuer, Ave');
INSERT INTO customer (c_id,name,address) VALUES (47,'Hasad Frye','P.O. Box 238, 7582 Arcu Avenue');
INSERT INTO customer (c_id,name,address) VALUES (48,'Brandon Vang','P.O. Box 203, 2424 Fusce Street');
INSERT INTO customer (c_id,name,address) VALUES (49,'Conan Bowen','999-9487 Eu Avenue');
INSERT INTO customer (c_id,name,address) VALUES (50,'Joel Dalton','375 Integer Avenue');
INSERT INTO customer (c_id,name,address) VALUES (51,'Josiah Page','P.O. Box 949, 9686 Elit. Rd.');
INSERT INTO customer (c_id,name,address) VALUES (52,'Benedict Calderon','940-6040 Nec Rd.');
INSERT INTO customer (c_id,name,address) VALUES (53,'Dillon Saunders','P.O. Box 106, 5794 Fringilla, Av.');
INSERT INTO customer (c_id,name,address) VALUES (54,'Declan Gross','434-9185 Dolor Av.');
INSERT INTO customer (c_id,name,address) VALUES (55,'Alec Cooke','Ap #173-4186 Sit Rd.');
INSERT INTO customer (c_id,name,address) VALUES (56,'Brandon Morgan','6968 Nec Rd.');
INSERT INTO customer (c_id,name,address) VALUES (57,'Wade Stokes','P.O. Box 755, 5222 Orci. Av.');
INSERT INTO customer (c_id,name,address) VALUES (58,'Connor Parks','8947 Duis Avenue');
INSERT INTO customer (c_id,name,address) VALUES (59,'Eagan Colon','5686 Vulputate St.');
INSERT INTO customer (c_id,name,address) VALUES (60,'Dean Williamson','P.O. Box 228, 1341 Mauris. Rd.');
INSERT INTO customer (c_id,name,address) VALUES (61,'Galvin Meadows','P.O. Box 142, 8100 Tempus Rd.');
INSERT INTO customer (c_id,name,address) VALUES (62,'Moses Blair','101-5911 Nunc St.');
INSERT INTO customer (c_id,name,address) VALUES (63,'Magee Bowman','8686 A Ave');
INSERT INTO customer (c_id,name,address) VALUES (64,'Yuli Hood','Ap #523-9412 Phasellus St.');
INSERT INTO customer (c_id,name,address) VALUES (65,'Mannix Hernandez','Ap #793-8367 Nulla Avenue');
INSERT INTO customer (c_id,name,address) VALUES (66,'Rigel Gilmore','P.O. Box 487, 9631 Etiam Road');
INSERT INTO customer (c_id,name,address) VALUES (67,'Honorato Reeves','257-5782 Arcu. St.');
INSERT INTO customer (c_id,name,address) VALUES (68,'Lars Gilbert','7294 Vitae, Ave');
INSERT INTO customer (c_id,name,address) VALUES (69,'Silas Finch','Ap #841-6030 Ridiculus Avenue');
INSERT INTO customer (c_id,name,address) VALUES (70,'Samson Andrews','887-1219 Mi Road');
INSERT INTO customer (c_id,name,address) VALUES (71,'Dennis Larson','Ap #547-128 Nunc Avenue');
INSERT INTO customer (c_id,name,address) VALUES (72,'Vance Cummings','3168 Nonummy. Ave');
INSERT INTO customer (c_id,name,address) VALUES (73,'Valentine Day','660-9706 Velit. Av.');
INSERT INTO customer (c_id,name,address) VALUES (74,'Timothy Robertson','313-4345 Magnis Street');
INSERT INTO customer (c_id,name,address) VALUES (75,'Shad Bowman','2673 Arcu. Av.');
INSERT INTO customer (c_id,name,address) VALUES (76,'James Benson','Ap #873-949 Dolor Av.');
INSERT INTO customer (c_id,name,address) VALUES (77,'Davis Mason','6017 Eros Ave');
INSERT INTO customer (c_id,name,address) VALUES (78,'Jacob Booker','Ap #920-4051 Sed Street');
INSERT INTO customer (c_id,name,address) VALUES (79,'Fletcher Doyle','930-2117 Mollis Av.');
INSERT INTO customer (c_id,name,address) VALUES (80,'Nasim Park','Ap #421-2835 Justo. Ave');
INSERT INTO customer (c_id,name,address) VALUES (81,'Louis Whitfield','P.O. Box 862, 4933 c_Id, Road');
INSERT INTO customer (c_id,name,address) VALUES (82,'Melvin Davis','197-3697 Interdum Rd.');
INSERT INTO customer (c_id,name,address) VALUES (83,'Arthur Chang','412-5959 Venenatis Ave');
INSERT INTO customer (c_id,name,address) VALUES (84,'Maxwell Morrow','9575 Nec Ave');
INSERT INTO customer (c_id,name,address) VALUES (85,'Harlan Farmer','Ap #607-6034 Quis, Rd.');
INSERT INTO customer (c_id,name,address) VALUES (86,'George Yates','4451 Fusce Avenue');
INSERT INTO customer (c_id,name,address) VALUES (87,'Wylie Webster','742-2887 Malesuada Av.');
INSERT INTO customer (c_id,name,address) VALUES (88,'Jacob Britt','2655 Arcu Rd.');
INSERT INTO customer (c_id,name,address) VALUES (89,'Jonas Willis','572-7759 Proin Rd.');
INSERT INTO customer (c_id,name,address) VALUES (90,'Troy Nunez','996-2629 Neque. Road');
INSERT INTO customer (c_id,name,address) VALUES (91,'Kuame Hopper','657-5138 Eleifend St.');
INSERT INTO customer (c_id,name,address) VALUES (92,'Dominic Dawson','Ap #728-9143 Felis. Rd.');
INSERT INTO customer (c_id,name,address) VALUES (93,'Denton Barnes','P.O. Box 503, 5773 Aenean Av.');
INSERT INTO customer (c_id,name,address) VALUES (94,'Henry Branch','P.O. Box 201, 3692 Massa Av.');
INSERT INTO customer (c_id,name,address) VALUES (95,'Hilel Clay','939-4370 Eget Rd.');
INSERT INTO customer (c_id,name,address) VALUES (96,'Armando Rivera','332-9094 Ultrices St.');
INSERT INTO customer (c_id,name,address) VALUES (97,'Darius Stevenson','Ap #243-4856 Iaculis Rd.');
INSERT INTO customer (c_id,name,address) VALUES (98,'Merritt Torres','840-3620 Dignissim Av.');
INSERT INTO customer (c_id,name,address) VALUES (99,'Finn Huff','Ap #502-5993 Viverra. St.');
INSERT INTO customer (c_id,name,address) VALUES (100,'Walter Huber','781-8270 Velit. Road');
INSERT INTO customer (c_id,name,address) VALUES (101,'Duncan Avila','804-5658 Posuere Avenue');
INSERT INTO customer (c_id,name,address) VALUES (102,'Hunter Key','752-5772 Egestas, St.');
INSERT INTO customer (c_id,name,address) VALUES (103,'Cadman Ortiz','760-3082 Ornare Avenue');
INSERT INTO customer (c_id,name,address) VALUES (104,'Zeph Marshall','2045 Consectetuer Ave');
INSERT INTO customer (c_id,name,address) VALUES (105,'Wang Santiago','Ap #692-1617 Maecenas Ave');
INSERT INTO customer (c_id,name,address) VALUES (106,'Leo Berger','312-8605 Elit Rd.');
INSERT INTO customer (c_id,name,address) VALUES (107,'Devin Carson','Ap #764-1661 Sagittis St.');
INSERT INTO customer (c_id,name,address) VALUES (108,'Wallace Berry','774-8129 Hendrerit. Rd.');
INSERT INTO customer (c_id,name,address) VALUES (109,'Elijah Edwards','Ap #433-5461 Nunc Rd.');
INSERT INTO customer (c_id,name,address) VALUES (110,'Rooney Barton','8090 Massa. Road');
INSERT INTO customer (c_id,name,address) VALUES (111,'Bruce Dunlap','4286 Iaculis Road');
INSERT INTO customer (c_id,name,address) VALUES (112,'Erasmus Barton','1764 Quis Rd.');
INSERT INTO customer (c_id,name,address) VALUES (113,'Nehru Suarez','2539 Turpis Street');
INSERT INTO customer (c_id,name,address) VALUES (114,'Ferris Chapman','5682 Nec St.');
INSERT INTO customer (c_id,name,address) VALUES (115,'Harlan Patterson','Ap #220-9792 Nisi St.');
INSERT INTO customer (c_id,name,address) VALUES (116,'Tobias Nieves','8612 Netus Road');
INSERT INTO customer (c_id,name,address) VALUES (117,'Stephen Watkins','968-5941 Enim. Road');
INSERT INTO customer (c_id,name,address) VALUES (118,'Isaiah Willis','P.O. Box 225, 5525 Urna Rd.');
INSERT INTO customer (c_id,name,address) VALUES (119,'Lewis Mcintosh','208-1765 Velit. Ave');
INSERT INTO customer (c_id,name,address) VALUES (120,'Davis Tanner','349-3767 Magna. St.');
INSERT INTO customer (c_id,name,address) VALUES (121,'Yasir Roman','P.O. Box 157, 5174 Mollis St.');
INSERT INTO customer (c_id,name,address) VALUES (122,'Keefe Jacobson','6519 Vitae, St.');
INSERT INTO customer (c_id,name,address) VALUES (123,'Melvin Rollins','Ap #117-7025 Nullam Ave');
INSERT INTO customer (c_id,name,address) VALUES (124,'Lucian Sellers','3165 Tellus. Rd.');
INSERT INTO customer (c_id,name,address) VALUES (125,'Alden Morales','6352 Et St.');
INSERT INTO customer (c_id,name,address) VALUES (126,'Devin Bates','9623 Nunc Rd.');
INSERT INTO customer (c_id,name,address) VALUES (127,'Davis Roach','685-6051 Tellus Street');
INSERT INTO customer (c_id,name,address) VALUES (128,'Jared Pruitt','P.O. Box 430, 456 Netus St.');
INSERT INTO customer (c_id,name,address) VALUES (129,'Elliott Fox','Ap #556-4024 Interdum. St.');
INSERT INTO customer (c_id,name,address) VALUES (130,'Griffin Cameron','6265 Nunc St.');
INSERT INTO customer (c_id,name,address) VALUES (131,'Daniel Bennett','344-4710 Nulla. St.');
INSERT INTO customer (c_id,name,address) VALUES (132,'Chaim Livingston','939-6380 Leo Ave');
INSERT INTO customer (c_id,name,address) VALUES (133,'Clark Christensen','5805 Eros Rd.');
INSERT INTO customer (c_id,name,address) VALUES (134,'Rooney England','9908 At Av.');
INSERT INTO customer (c_id,name,address) VALUES (135,'Ivor Stanley','Ap #751-6306 Libero. St.');
INSERT INTO customer (c_id,name,address) VALUES (136,'Eric Buck','8355 Urna. Rd.');
INSERT INTO customer (c_id,name,address) VALUES (137,'Elliott Mcclain','Ap #230-4090 Quisque St.');
INSERT INTO customer (c_id,name,address) VALUES (138,'Hiram Stout','984-9560 Nec, Ave');
INSERT INTO customer (c_id,name,address) VALUES (139,'Isaac Combs','P.O. Box 551, 6726 Cras Av.');
INSERT INTO customer (c_id,name,address) VALUES (140,'Moses Maxwell','851-6954 Ornare Rd.');
INSERT INTO customer (c_id,name,address) VALUES (141,'Norman Buckley','680-8674 Pellentesque Avenue');
INSERT INTO customer (c_id,name,address) VALUES (142,'Barclay Spencer','4586 In Street');
INSERT INTO customer (c_id,name,address) VALUES (143,'Thane Olsen','P.O. Box 722, 8948 Lacus. Rd.');
INSERT INTO customer (c_id,name,address) VALUES (144,'Stewart Bartlett','Ap #731-5637 Amet St.');
INSERT INTO customer (c_id,name,address) VALUES (145,'Salvador Walsh','411-6745 Etiam Rd.');
INSERT INTO customer (c_id,name,address) VALUES (146,'Clarke Hester','P.O. Box 927, 7086 Proin Av.');
INSERT INTO customer (c_id,name,address) VALUES (147,'Caesar Cohen','650-1949 Turpis Rd.');
INSERT INTO customer (c_id,name,address) VALUES (148,'Honorato Cobb','P.O. Box 519, 5670 Quam St.');
INSERT INTO customer (c_id,name,address) VALUES (149,'Graham Blake','P.O. Box 874, 4158 Ut St.');
INSERT INTO customer (c_id,name,address) VALUES (150,'Gil Rosales','Ap #997-4907 Et, St.');
INSERT INTO customer (c_id,name,address) VALUES (151,'Linus Hernandez','P.O. Box 600, 3788 Donec St.');
INSERT INTO customer (c_id,name,address) VALUES (152,'Dillon Fulton','Ap #179-9159 Non St.');
INSERT INTO customer (c_id,name,address) VALUES (153,'Curran Cooper','4666 Felis, Rd.');
INSERT INTO customer (c_id,name,address) VALUES (154,'Ira Gates','Ap #159-9548 Magna, Street');
INSERT INTO customer (c_id,name,address) VALUES (155,'Abdul Larsen','Ap #180-6337 Feugiat Rd.');
INSERT INTO customer (c_id,name,address) VALUES (156,'Hedley Chambers','2035 Vulputate, Avenue');
INSERT INTO customer (c_id,name,address) VALUES (157,'Carson Anthony','Ap #151-6458 Elit St.');
INSERT INTO customer (c_id,name,address) VALUES (158,'Lamar Atkins','P.O. Box 507, 7598 Ullamcorper Street');
INSERT INTO customer (c_id,name,address) VALUES (159,'Burke Holland','Ap #117-6564 Luctus Av.');
INSERT INTO customer (c_id,name,address) VALUES (160,'Lars Mccarty','Ap #346-3377 Varius Road');
INSERT INTO customer (c_id,name,address) VALUES (161,'Christian Bullock','Ap #608-9631 Donec Ave');
INSERT INTO customer (c_id,name,address) VALUES (162,'Hamilton Mejia','346-3980 Hendrerit Street');
INSERT INTO customer (c_id,name,address) VALUES (163,'Hector Long','P.O. Box 511, 2478 Lectus St.');
INSERT INTO customer (c_id,name,address) VALUES (164,'Jelani Cooke','Ap #780-7174 Enim. Avenue');
INSERT INTO customer (c_id,name,address) VALUES (165,'Denton Quinn','P.O. Box 811, 9126 Ullamcorper St.');
INSERT INTO customer (c_id,name,address) VALUES (166,'Merrill Moon','P.O. Box 147, 629 Diam St.');
INSERT INTO customer (c_id,name,address) VALUES (167,'Anthony Whitley','P.O. Box 855, 3298 Nec Avenue');
INSERT INTO customer (c_id,name,address) VALUES (168,'Leroy Elliott','Ap #161-8482 Egestas. Rd.');
INSERT INTO customer (c_id,name,address) VALUES (169,'Walker Shields','520-8075 Aenean Street');
INSERT INTO customer (c_id,name,address) VALUES (170,'Brody Tucker','Ap #340-2775 Mauris St.');
INSERT INTO customer (c_id,name,address) VALUES (171,'Jonas Underwood','8335 Dolor Rd.');
INSERT INTO customer (c_id,name,address) VALUES (172,'Philip Huber','5200 Augue. Rd.');
INSERT INTO customer (c_id,name,address) VALUES (173,'Hunter Hammond','Ap #108-7147 Nunc Ave');
INSERT INTO customer (c_id,name,address) VALUES (174,'Tyler Steele','Ap #254-9661 Elementum, Rd.');
INSERT INTO customer (c_id,name,address) VALUES (175,'Eagan Luna','3549 Non, Street');
INSERT INTO customer (c_id,name,address) VALUES (176,'Merrill Good','1010 Posuere Road');
INSERT INTO customer (c_id,name,address) VALUES (177,'Ronan Weeks','Ap #278-8474 Mus. Ave');
INSERT INTO customer (c_id,name,address) VALUES (178,'Jonas Mcmillan','147-9306 Consectetuer Av.');
INSERT INTO customer (c_id,name,address) VALUES (179,'Calvin Vasquez','Ap #750-1714 Lacus. Ave');
INSERT INTO customer (c_id,name,address) VALUES (180,'Driscoll Cherry','8618 Pellentesque. Street');
INSERT INTO customer (c_id,name,address) VALUES (181,'Macon Baird','Ap #625-3089 Tincidunt. Rd.');
INSERT INTO customer (c_id,name,address) VALUES (182,'Bruno Sutton','2633 Duis Road');
INSERT INTO customer (c_id,name,address) VALUES (183,'Bert Garza','9479 Mi Street');
INSERT INTO customer (c_id,name,address) VALUES (184,'Chase Oneal','3236 Non, Av.');
INSERT INTO customer (c_id,name,address) VALUES (185,'Stewart Sykes','265-6827 Augue Street');
INSERT INTO customer (c_id,name,address) VALUES (186,'Gareth Medina','Ap #172-9466 Vitae, St.');
INSERT INTO customer (c_id,name,address) VALUES (187,'Norman Manning','883-616 Sed Rd.');
INSERT INTO customer (c_id,name,address) VALUES (188,'Barrett Duran','449-1084 Sed, Road');
INSERT INTO customer (c_id,name,address) VALUES (189,'Zane Clements','5039 Et Rd.');
INSERT INTO customer (c_id,name,address) VALUES (190,'Salvador Stein','P.O. Box 529, 7896 Penatibus Av.');
INSERT INTO customer (c_id,name,address) VALUES (191,'Drew Morton','8617 Mi Avenue');
INSERT INTO customer (c_id,name,address) VALUES (192,'Phillip Valenzuela','4300 At St.');
INSERT INTO customer (c_id,name,address) VALUES (193,'Giacomo Lynn','P.O. Box 182, 5331 Eu Street');
INSERT INTO customer (c_id,name,address) VALUES (194,'Dane Cole','Ap #998-261 Ante, Ave');
INSERT INTO customer (c_id,name,address) VALUES (195,'David Sparks','Ap #623-9035 Neque St.');
INSERT INTO customer (c_id,name,address) VALUES (196,'Buckminster Noel','P.O. Box 159, 617 Fermentum Ave');
INSERT INTO customer (c_id,name,address) VALUES (197,'Salvador Whitley','957-1235 Tortor. St.');
INSERT INTO customer (c_id,name,address) VALUES (198,'Gray Warren','Ap #911-752 Nullam Rd.');
INSERT INTO customer (c_id,name,address) VALUES (199,'Bert Mckee','Ap #719-9482 Felis Road');
INSERT INTO customer (c_id,name,address) VALUES (200,'Reed Ratliff','9327 Feugiat Street');
INSERT INTO customer (c_id,name,address) VALUES (201,'Donovan Schmidt','Ap #543-2521 Facilisis Rd.');
INSERT INTO customer (c_id,name,address) VALUES (202,'Gage Gilbert','954-7448 Ut Rd.');
INSERT INTO customer (c_id,name,address) VALUES (203,'Chaney Evans','7357 Duis St.');
INSERT INTO customer (c_id,name,address) VALUES (204,'Berk Howard','5414 Suspendisse Street');
INSERT INTO customer (c_id,name,address) VALUES (205,'Alden Neal','P.O. Box 889, 3173 Vitae Ave');
INSERT INTO customer (c_id,name,address) VALUES (206,'Byron Ellison','1466 Pharetra. St.');
INSERT INTO customer (c_id,name,address) VALUES (207,'Xavier Barber','Ap #522-3033 Euismod Avenue');
INSERT INTO customer (c_id,name,address) VALUES (208,'Cooper Cabrera','P.O. Box 284, 3677 Sodales Rd.');
INSERT INTO customer (c_id,name,address) VALUES (209,'Ferris Underwood','853-1646 Risus Rd.');
INSERT INTO customer (c_id,name,address) VALUES (210,'Colin Mckenzie','Ap #775-4919 Bibendum Street');
INSERT INTO customer (c_id,name,address) VALUES (211,'Keefe Ochoa','P.O. Box 223, 3783 Cursus, Avenue');
INSERT INTO customer (c_id,name,address) VALUES (212,'Clayton Macias','P.O. Box 440, 3519 Tincidunt, Street');
INSERT INTO customer (c_id,name,address) VALUES (213,'Ralph Pearson','Ap #900-2456 Nibh. Rd.');
INSERT INTO customer (c_id,name,address) VALUES (214,'Joseph Hopkins','P.O. Box 389, 5627 Est Rd.');
INSERT INTO customer (c_id,name,address) VALUES (215,'Caesar William','Ap #381-4676 Neque Rd.');
INSERT INTO customer (c_id,name,address) VALUES (216,'Barry Davenport','550-998 Elementum St.');
INSERT INTO customer (c_id,name,address) VALUES (217,'Quinlan Moon','P.O. Box 560, 9508 Quam. Av.');
INSERT INTO customer (c_id,name,address) VALUES (218,'Orlando Morris','6062 Augue Rd.');
INSERT INTO customer (c_id,name,address) VALUES (219,'Cade Savage','Ap #540-778 Ullamcorper St.');
INSERT INTO customer (c_id,name,address) VALUES (220,'Joshua Acevedo','443-5448 Phasellus Rd.');
INSERT INTO customer (c_id,name,address) VALUES (221,'Stone Romero','548-2597 Consectetuer, Street');
INSERT INTO customer (c_id,name,address) VALUES (222,'Callum Winters','761-1794 Quam Ave');
INSERT INTO customer (c_id,name,address) VALUES (223,'Chancellor Cote','883 Commodo Rd.');
INSERT INTO customer (c_id,name,address) VALUES (224,'Quamar Avila','772-4782 Mollis. Av.');
INSERT INTO customer (c_id,name,address) VALUES (225,'Tiger Strickland','P.O. Box 890, 9669 Vel, Avenue');
INSERT INTO customer (c_id,name,address) VALUES (226,'Xander Rosario','P.O. Box 936, 458 Pede Road');
INSERT INTO customer (c_id,name,address) VALUES (227,'Dorian Simon','P.O. Box 297, 640 Lacinia. Ave');
INSERT INTO customer (c_id,name,address) VALUES (228,'Zephania Bailey','169 Ornare Street');
INSERT INTO customer (c_id,name,address) VALUES (229,'Igor Cherry','1826 Elementum Rd.');
INSERT INTO customer (c_id,name,address) VALUES (230,'Christian Myers','P.O. Box 345, 1405 Orci Rd.');
INSERT INTO customer (c_id,name,address) VALUES (231,'Jerry Douglas','980 Vitae Rd.');
INSERT INTO customer (c_id,name,address) VALUES (232,'Ivan Rasmussen','5578 Lobortis St.');
INSERT INTO customer (c_id,name,address) VALUES (233,'Kieran Francis','Ap #134-4672 Sagittis Street');
INSERT INTO customer (c_id,name,address) VALUES (234,'Jared Holden','Ap #908-5485 Ut Ave');
INSERT INTO customer (c_id,name,address) VALUES (235,'Hayden Stanley','Ap #638-8331 Euismod Rd.');
INSERT INTO customer (c_id,name,address) VALUES (236,'Zephania Curry','P.O. Box 406, 488 Est St.');
INSERT INTO customer (c_id,name,address) VALUES (237,'Mufutau Mcclure','737-3148 Libero. Street');
INSERT INTO customer (c_id,name,address) VALUES (238,'Joel Hutchinson','2520 Tristique Road');
INSERT INTO customer (c_id,name,address) VALUES (239,'Isaac Jordan','581-9407 Euismod Ave');
INSERT INTO customer (c_id,name,address) VALUES (240,'Fulton George','191-4789 Ornare, St.');
INSERT INTO customer (c_id,name,address) VALUES (241,'Keaton Cobb','P.O. Box 865, 6205 Arcu. Ave');
INSERT INTO customer (c_id,name,address) VALUES (242,'Dennis Harmon','2695 Consequat Av.');
INSERT INTO customer (c_id,name,address) VALUES (243,'Rudyard Garza','560-4531 Bibendum. Av.');
INSERT INTO customer (c_id,name,address) VALUES (244,'Leonard Weiss','P.O. Box 667, 6223 Integer Avenue');
INSERT INTO customer (c_id,name,address) VALUES (245,'Hasad Mckinney','Ap #446-6953 Enim. St.');
INSERT INTO customer (c_id,name,address) VALUES (246,'Gregory Sykes','Ap #957-1067 Aliquam St.');
INSERT INTO customer (c_id,name,address) VALUES (247,'Brendan Hudson','8923 Elementum Rd.');
INSERT INTO customer (c_id,name,address) VALUES (248,'Acton Shelton','545-8071 Consequat, Avenue');
INSERT INTO customer (c_id,name,address) VALUES (249,'Jeremy Kaufman','Ap #987-6321 Lobortis Road');
INSERT INTO customer (c_id,name,address) VALUES (250,'Gray Salas','797-1301 Condimentum. Street');
INSERT INTO customer (c_id,name,address) VALUES (251,'Rudyard Patrick','P.O. Box 752, 1828 Duis Street');
INSERT INTO customer (c_id,name,address) VALUES (252,'Allen Daniel','467-6840 Sed Ave');
INSERT INTO customer (c_id,name,address) VALUES (253,'Forrest Daugherty','Ap #249-2789 Nunc Ave');
INSERT INTO customer (c_id,name,address) VALUES (254,'Dalton Riddle','Ap #634-1927 Dictum Rd.');
INSERT INTO customer (c_id,name,address) VALUES (255,'Raphael Kramer','367-7873 Cras St.');
INSERT INTO customer (c_id,name,address) VALUES (256,'Lawrence Blake','P.O. Box 338, 8812 Consectetuer St.');
INSERT INTO customer (c_id,name,address) VALUES (257,'Omar Patel','Ap #162-7119 Feugiat Ave');
INSERT INTO customer (c_id,name,address) VALUES (258,'Leonard Gill','253-6936 Blandit Av.');
INSERT INTO customer (c_id,name,address) VALUES (259,'Wang Randolph','P.O. Box 429, 6048 Diam Rd.');
INSERT INTO customer (c_id,name,address) VALUES (260,'Leonard Conway','P.O. Box 391, 9350 Curabitur Street');
INSERT INTO customer (c_id,name,address) VALUES (261,'Leroy Norman','4335 Volutpat. Ave');
INSERT INTO customer (c_id,name,address) VALUES (262,'Sean Hyde','845-1250 Enim. Rd.');
INSERT INTO customer (c_id,name,address) VALUES (263,'Arthur Rosales','422-877 Auctor Rd.');
INSERT INTO customer (c_id,name,address) VALUES (264,'Drake Finley','5711 Dictum St.');
INSERT INTO customer (c_id,name,address) VALUES (265,'Flynn Thompson','2391 Sit Rd.');
INSERT INTO customer (c_id,name,address) VALUES (266,'Cade Francis','8831 Nullam Avenue');
INSERT INTO customer (c_id,name,address) VALUES (267,'Henry Stuart','P.O. Box 521, 8737 Pede Ave');
INSERT INTO customer (c_id,name,address) VALUES (268,'Neville Gardner','521 Nam Road');
INSERT INTO customer (c_id,name,address) VALUES (269,'Burke Boyer','511-770 Turpis Av.');
INSERT INTO customer (c_id,name,address) VALUES (270,'Addison Guerra','1046 Ipsum Road');
INSERT INTO customer (c_id,name,address) VALUES (271,'Scott House','287-2436 Mauris Rd.');
INSERT INTO customer (c_id,name,address) VALUES (272,'Allistair Burt','P.O. Box 761, 6841 Proin Ave');
INSERT INTO customer (c_id,name,address) VALUES (273,'Jordan Everett','806-6627 Nunc Road');
INSERT INTO customer (c_id,name,address) VALUES (274,'Warren Ingram','3455 Mauris Av.');
INSERT INTO customer (c_id,name,address) VALUES (275,'Caldwell Dunn','552-7061 Risus. Rd.');
INSERT INTO customer (c_id,name,address) VALUES (276,'Phelan Dixon','879-3333 Dictum. Rd.');
INSERT INTO customer (c_id,name,address) VALUES (277,'Branden Morris','6433 Nunc Rd.');
INSERT INTO customer (c_id,name,address) VALUES (278,'Brody Cruz','191-8269 Etiam St.');
INSERT INTO customer (c_id,name,address) VALUES (279,'Baker Barnett','1116 Massa. Road');
INSERT INTO customer (c_id,name,address) VALUES (280,'Hop Campbell','Ap #946-7458 Justo Ave');
INSERT INTO customer (c_id,name,address) VALUES (281,'Quamar Atkins','728-7152 Ligula. Avenue');
INSERT INTO customer (c_id,name,address) VALUES (282,'Dorian Brewer','P.O. Box 425, 5037 Cum Ave');
INSERT INTO customer (c_id,name,address) VALUES (283,'Cadman Nicholson','P.O. Box 468, 6143 Massa. Rd.');
INSERT INTO customer (c_id,name,address) VALUES (284,'Keegan Clarke','293-1335 Morbi Rd.');
INSERT INTO customer (c_id,name,address) VALUES (285,'Acton Todd','397-5076 Sit Avenue');
INSERT INTO customer (c_id,name,address) VALUES (286,'Amir Kirkland','Ap #252-3474 Nunc. Street');
INSERT INTO customer (c_id,name,address) VALUES (287,'Ryder Savage','Ap #208-2467 Lobortis Av.');
INSERT INTO customer (c_id,name,address) VALUES (288,'Owen Donaldson','731 Eu, St.');
INSERT INTO customer (c_id,name,address) VALUES (289,'Berk Chen','P.O. Box 440, 3697 Orci St.');
INSERT INTO customer (c_id,name,address) VALUES (290,'Asher Roberson','899-4573 Iaculis Street');
INSERT INTO customer (c_id,name,address) VALUES (291,'Aristotle Rich','938-2551 Sit Rd.');
INSERT INTO customer (c_id,name,address) VALUES (292,'Nicholas Mcpherson','Ap #318-8732 Elementum Av.');
INSERT INTO customer (c_id,name,address) VALUES (293,'Mohammad York','239-9138 Aliquam Road');
INSERT INTO customer (c_id,name,address) VALUES (294,'Nasim Wall','Ap #229-9694 In St.');
INSERT INTO customer (c_id,name,address) VALUES (295,'Hector Carlson','Ap #172-1078 Morbi Av.');
INSERT INTO customer (c_id,name,address) VALUES (296,'Kane Mcgee','P.O. Box 682, 7299 Ut St.');
INSERT INTO customer (c_id,name,address) VALUES (297,'Hunter Alford','4222 Malesuada. Road');
INSERT INTO customer (c_id,name,address) VALUES (298,'Elliott Sawyer','9720 Ipsum Road');
INSERT INTO customer (c_id,name,address) VALUES (299,'Allen Lewis','568-3823 Pharetra. Av.');
INSERT INTO customer (c_id,name,address) VALUES (300,'Nicholas Sloan','Ap #691-1076 Augue Rd.');
INSERT INTO customer (c_id,name,address) VALUES (301,'Eric Carey','Ap #397-6536 Gravida Av.');
INSERT INTO customer (c_id,name,address) VALUES (302,'Daquan Lindsay','P.O. Box 551, 1212 At, St.');
INSERT INTO customer (c_id,name,address) VALUES (303,'Lester Vasquez','Ap #121-5349 Dui. Ave');
INSERT INTO customer (c_id,name,address) VALUES (304,'Jason Cox','502-482 Vitae Rd.');
INSERT INTO customer (c_id,name,address) VALUES (305,'Drake Jimenez','P.O. Box 288, 6146 Tincidunt Street');
INSERT INTO customer (c_id,name,address) VALUES (306,'Craig Bush','641-3701 Vivamus St.');
INSERT INTO customer (c_id,name,address) VALUES (307,'Reed Baldwin','Ap #598-6422 Mauris Road');
INSERT INTO customer (c_id,name,address) VALUES (308,'Aidan Mitchell','Ap #397-8829 Neque. St.');
INSERT INTO customer (c_id,name,address) VALUES (309,'Avram Banks','626-9180 Vel, Av.');
INSERT INTO customer (c_id,name,address) VALUES (310,'Addison Combs','451-6257 Mollis Street');
INSERT INTO customer (c_id,name,address) VALUES (311,'Benedict Wade','Ap #997-1850 Libero Ave');
INSERT INTO customer (c_id,name,address) VALUES (312,'Blaze Sherman','Ap #452-3656 Vitae, Ave');
INSERT INTO customer (c_id,name,address) VALUES (313,'Thor Stanley','Ap #502-6681 Sem St.');
INSERT INTO customer (c_id,name,address) VALUES (314,'Jesse Rush','612-126 Malesuada. Av.');
INSERT INTO customer (c_id,name,address) VALUES (315,'Clarke Bridges','Ap #328-778 Pharetra. Av.');
INSERT INTO customer (c_id,name,address) VALUES (316,'Slade Lara','1184 Ornare, Rd.');
INSERT INTO customer (c_id,name,address) VALUES (317,'Boris Brock','141-8612 Ullamcorper. St.');
INSERT INTO customer (c_id,name,address) VALUES (318,'Paki Cooper','Ap #777-6360 Velit. Road');
INSERT INTO customer (c_id,name,address) VALUES (319,'Dustin Guerrero','P.O. Box 450, 3507 Mauris Avenue');
INSERT INTO customer (c_id,name,address) VALUES (320,'Judah Workman','P.O. Box 110, 879 Vel Rd.');
INSERT INTO customer (c_id,name,address) VALUES (321,'Samuel Montgomery','818-3593 Mauris Road');
INSERT INTO customer (c_id,name,address) VALUES (322,'Merrill Morales','3140 Eget Ave');
INSERT INTO customer (c_id,name,address) VALUES (323,'Graiden Bradley','6503 Ridiculus Av.');
INSERT INTO customer (c_id,name,address) VALUES (324,'Wing Taylor','P.O. Box 441, 8342 Egestas, Av.');
INSERT INTO customer (c_id,name,address) VALUES (325,'Octavius Russo','Ap #534-615 Mauris Street');
INSERT INTO customer (c_id,name,address) VALUES (326,'Austin Howell','P.O. Box 837, 998 Adipiscing Av.');
INSERT INTO customer (c_id,name,address) VALUES (327,'Fuller Dennis','395 Vel, Street');
INSERT INTO customer (c_id,name,address) VALUES (328,'Jasper Roy','P.O. Box 890, 3603 Sollicitudin Ave');
INSERT INTO customer (c_id,name,address) VALUES (329,'Tiger Gould','1106 Est Rd.');
INSERT INTO customer (c_id,name,address) VALUES (330,'Keith Stone','474-2492 Hendrerit St.');
INSERT INTO customer (c_id,name,address) VALUES (331,'Clarke Hampton','P.O. Box 761, 5269 A, Ave');
INSERT INTO customer (c_id,name,address) VALUES (332,'Mason Fernandez','P.O. Box 107, 7378 Quisque Av.');
INSERT INTO customer (c_id,name,address) VALUES (333,'Roth Bennett','Ap #285-7096 In Road');
INSERT INTO customer (c_id,name,address) VALUES (334,'Hu Green','P.O. Box 878, 7620 Ipsum Ave');
INSERT INTO customer (c_id,name,address) VALUES (335,'George Richards','3519 Vestibulum Rd.');
INSERT INTO customer (c_id,name,address) VALUES (336,'Christopher Adams','P.O. Box 941, 214 Blandit St.');
INSERT INTO customer (c_id,name,address) VALUES (337,'Malcolm Francis','575 Phasellus Street');
INSERT INTO customer (c_id,name,address) VALUES (338,'Oren Blackburn','Ap #542-548 Porttitor Ave');
INSERT INTO customer (c_id,name,address) VALUES (339,'Brian Joyner','P.O. Box 182, 8026 Ultricies Street');
INSERT INTO customer (c_id,name,address) VALUES (340,'Jasper James','841-1499 Elit, Road');
INSERT INTO customer (c_id,name,address) VALUES (341,'Jared Goodman','5868 Ut, Av.');
INSERT INTO customer (c_id,name,address) VALUES (342,'Kato Mclaughlin','1930 Tempus Rd.');
INSERT INTO customer (c_id,name,address) VALUES (343,'Samson Welch','P.O. Box 884, 7082 Malesuada Ave');
INSERT INTO customer (c_id,name,address) VALUES (344,'Henry Rosario','P.O. Box 370, 9956 Etiam Ave');
INSERT INTO customer (c_id,name,address) VALUES (345,'Dalton William','812-118 Cursus Ave');
INSERT INTO customer (c_id,name,address) VALUES (346,'Quinlan Knox','Ap #952-2107 Molestie. Avenue');
INSERT INTO customer (c_id,name,address) VALUES (347,'Xander Lynch','Ap #237-5314 Sit Rd.');
INSERT INTO customer (c_id,name,address) VALUES (348,'Uriel Goodman','460-9713 Posuere St.');
INSERT INTO customer (c_id,name,address) VALUES (349,'Daquan Everett','Ap #608-2202 Euismod St.');
INSERT INTO customer (c_id,name,address) VALUES (350,'Ray Garrett','Ap #764-9024 Vitae, Road');
INSERT INTO customer (c_id,name,address) VALUES (351,'Tyler Taylor','444-4347 Odio Rd.');
INSERT INTO customer (c_id,name,address) VALUES (352,'Holmes Kelley','6742 Nascetur St.');
INSERT INTO customer (c_id,name,address) VALUES (353,'Cadman Ratliff','P.O. Box 906, 1360 Rutrum St.');
INSERT INTO customer (c_id,name,address) VALUES (354,'Callum Rollins','Ap #832-1025 Consectetuer St.');
INSERT INTO customer (c_id,name,address) VALUES (355,'Zachery Jensen','4096 Ornare Rd.');
INSERT INTO customer (c_id,name,address) VALUES (356,'Erich Santos','3898 Diam. St.');
INSERT INTO customer (c_id,name,address) VALUES (357,'Reed Mercado','7040 Nonummy Street');
INSERT INTO customer (c_id,name,address) VALUES (358,'Tiger Mccall','P.O. Box 761, 475 Cum Avenue');
INSERT INTO customer (c_id,name,address) VALUES (359,'Vance Powell','7944 Augue. Av.');
INSERT INTO customer (c_id,name,address) VALUES (360,'Ivan Price','P.O. Box 298, 2372 Eget Street');
INSERT INTO customer (c_id,name,address) VALUES (361,'Stuart Knox','Ap #743-2644 Erat. Rd.');
INSERT INTO customer (c_id,name,address) VALUES (362,'Zephania Ware','1523 Scelerisque, Rd.');
INSERT INTO customer (c_id,name,address) VALUES (363,'Tanner Rowland','P.O. Box 655, 3005 Condimentum Ave');
INSERT INTO customer (c_id,name,address) VALUES (364,'Hop Mendoza','782-4090 Vitae Street');
INSERT INTO customer (c_id,name,address) VALUES (365,'Holmes Chan','P.O. Box 275, 9554 Vel, Avenue');
INSERT INTO customer (c_id,name,address) VALUES (366,'Cameron Johnston','8430 Aliquam St.');
INSERT INTO customer (c_id,name,address) VALUES (367,'Adam Mercer','Ap #242-2039 Sed Avenue');
INSERT INTO customer (c_id,name,address) VALUES (368,'Lucius Rich','P.O. Box 231, 6576 Convallis St.');
INSERT INTO customer (c_id,name,address) VALUES (369,'Edan Montoya','Ap #319-4131 Sodales St.');
INSERT INTO customer (c_id,name,address) VALUES (370,'Garrison Bullock','P.O. Box 267, 8327 Sit Street');
INSERT INTO customer (c_id,name,address) VALUES (371,'Kato Mcconnell','P.O. Box 295, 7926 Nulla. Street');
INSERT INTO customer (c_id,name,address) VALUES (372,'Burke Newman','111-4363 Dolor Avenue');
INSERT INTO customer (c_id,name,address) VALUES (373,'Salvador Giles','P.O. Box 464, 2526 Aliquam Rd.');
INSERT INTO customer (c_id,name,address) VALUES (374,'Stephen Moss','P.O. Box 854, 7889 Diam. Street');
INSERT INTO customer (c_id,name,address) VALUES (375,'Kelly Cunningham','Ap #429-6323 Pharetra. Avenue');
INSERT INTO customer (c_id,name,address) VALUES (376,'Solomon Johnson','P.O. Box 542, 6968 Amet Street');
INSERT INTO customer (c_id,name,address) VALUES (377,'Igor Pitts','2524 Erat Rd.');
INSERT INTO customer (c_id,name,address) VALUES (378,'Paki Mcgowan','443-4337 Gravida St.');
INSERT INTO customer (c_id,name,address) VALUES (379,'Byron Leblanc','Ap #930-4087 Non, Ave');
INSERT INTO customer (c_id,name,address) VALUES (380,'Thomas Sawyer','2599 Sit St.');
INSERT INTO customer (c_id,name,address) VALUES (381,'Harrison Herman','Ap #743-1194 Eget Rd.');
INSERT INTO customer (c_id,name,address) VALUES (382,'Quinn Gentry','2986 Dui, Avenue');
INSERT INTO customer (c_id,name,address) VALUES (383,'Baxter English','988-3807 Eu Av.');
INSERT INTO customer (c_id,name,address) VALUES (384,'Cedric Graham','4947 Augue Ave');
INSERT INTO customer (c_id,name,address) VALUES (385,'Ivan Sanders','646-3496 Hendrerit Ave');
INSERT INTO customer (c_id,name,address) VALUES (386,'Merritt Avery','9998 Aliquet Avenue');
INSERT INTO customer (c_id,name,address) VALUES (387,'Sylvester Townsend','587-3015 Faucibus Rd.');
INSERT INTO customer (c_id,name,address) VALUES (388,'Ahmed Rojas','P.O. Box 939, 1181 Lacus. Rd.');
INSERT INTO customer (c_id,name,address) VALUES (389,'Brett Melton','Ap #646-3407 Dignissim Ave');
INSERT INTO customer (c_id,name,address) VALUES (390,'Silas Henson','882-2625 Enim. St.');
INSERT INTO customer (c_id,name,address) VALUES (391,'Owen Grant','718 At St.');
INSERT INTO customer (c_id,name,address) VALUES (392,'Macon Gardner','506-9012 Dictum Av.');
INSERT INTO customer (c_id,name,address) VALUES (393,'Gage Reid','P.O. Box 623, 1807 Etiam Av.');
INSERT INTO customer (c_id,name,address) VALUES (394,'Andrew Navarro','Ap #357-4718 Massa Road');
INSERT INTO customer (c_id,name,address) VALUES (395,'Julian Armstrong','520-5307 Porttitor Rd.');
INSERT INTO customer (c_id,name,address) VALUES (396,'Baker Black','3312 Sed Rd.');
INSERT INTO customer (c_id,name,address) VALUES (397,'Nero Cole','397-9716 Non St.');
INSERT INTO customer (c_id,name,address) VALUES (398,'Gregory Little','Ap #546-2239 Integer Ave');
INSERT INTO customer (c_id,name,address) VALUES (399,'Mason Morse','9125 Nisl St.');
INSERT INTO customer (c_id,name,address) VALUES (400,'Omar Madden','9553 Ipsum. Av.');
INSERT INTO customer (c_id,name,address) VALUES (401,'Yardley Reynolds','961-7570 Posuere Rd.');
INSERT INTO customer (c_id,name,address) VALUES (402,'Harding Bond','P.O. Box 179, 1801 Diam St.');
INSERT INTO customer (c_id,name,address) VALUES (403,'Graham Lambert','Ap #142-4463 Aliquam St.');
INSERT INTO customer (c_id,name,address) VALUES (404,'Fuller Hartman','654-3778 Non St.');
INSERT INTO customer (c_id,name,address) VALUES (405,'Kamal Hubbard','803-5547 Suspendisse Avenue');
INSERT INTO customer (c_id,name,address) VALUES (406,'Rafael Pruitt','137-2096 Amet, St.');
INSERT INTO customer (c_id,name,address) VALUES (407,'Noah Mclaughlin','P.O. Box 914, 7951 Pede. Street');
INSERT INTO customer (c_id,name,address) VALUES (408,'Oleg Stanley','9391 Metus Street');
INSERT INTO customer (c_id,name,address) VALUES (409,'Quinn Bradford','P.O. Box 812, 8257 Tempus Av.');
INSERT INTO customer (c_id,name,address) VALUES (410,'Dustin Harrell','Ap #575-4765 Sed Road');
INSERT INTO customer (c_id,name,address) VALUES (411,'Oliver Ward','4882 Mauris Ave');
INSERT INTO customer (c_id,name,address) VALUES (412,'Ronan Yates','7092 Sed, St.');
INSERT INTO customer (c_id,name,address) VALUES (413,'Justin Flowers','367-1595 Proin St.');
INSERT INTO customer (c_id,name,address) VALUES (414,'Tyler Ramsey','Ap #229-2752 Posuere, Road');
INSERT INTO customer (c_id,name,address) VALUES (415,'Gil Carver','Ap #209-3857 Ac St.');
INSERT INTO customer (c_id,name,address) VALUES (416,'Luke Kidd','954-2993 Id Rd.');
INSERT INTO customer (c_id,name,address) VALUES (417,'Solomon Haynes','P.O. Box 973, 3935 Molestie St.');
INSERT INTO customer (c_id,name,address) VALUES (418,'Tobias Holcomb','Ap #131-8710 Vitae, Street');
INSERT INTO customer (c_id,name,address) VALUES (419,'Austin Sharpe','P.O. Box 113, 1443 Pede. Avenue');
INSERT INTO customer (c_id,name,address) VALUES (420,'Rudyard Lynn','Ap #445-2226 Iaculis, Rd.');
INSERT INTO customer (c_id,name,address) VALUES (421,'Ray Carter','530-837 Faucibus Avenue');
INSERT INTO customer (c_id,name,address) VALUES (422,'Charles Gilliam','707-7481 Fames Ave');
INSERT INTO customer (c_id,name,address) VALUES (423,'Kirk Klein','Ap #150-178 Egestas St.');
INSERT INTO customer (c_id,name,address) VALUES (424,'Abdul Ballard','P.O. Box 737, 8660 Augue Rd.');
INSERT INTO customer (c_id,name,address) VALUES (425,'Merritt Edwards','918-3627 A St.');
INSERT INTO customer (c_id,name,address) VALUES (426,'Levi Berry','P.O. Box 336, 3037 Donec Street');
INSERT INTO customer (c_id,name,address) VALUES (427,'Gavin Mckinney','5877 A, Street');
INSERT INTO customer (c_id,name,address) VALUES (428,'Wing Mckenzie','896-194 Nisl. Street');
INSERT INTO customer (c_id,name,address) VALUES (429,'Cameron Wall','P.O. Box 390, 6291 Neque. Road');
INSERT INTO customer (c_id,name,address) VALUES (430,'Emery Osborn','5675 Tortor Rd.');
INSERT INTO customer (c_id,name,address) VALUES (431,'Austin Goff','568-3398 Consectetuer Street');
INSERT INTO customer (c_id,name,address) VALUES (432,'Gavin Buckley','P.O. Box 526, 1563 Rutrum Road');
INSERT INTO customer (c_id,name,address) VALUES (433,'Macon Miranda','146-8772 Sapien. Av.');
INSERT INTO customer (c_id,name,address) VALUES (434,'Alec Roth','8648 Ipsum Rd.');
INSERT INTO customer (c_id,name,address) VALUES (435,'Todd Matthews','Ap #645-2087 Duis Ave');
INSERT INTO customer (c_id,name,address) VALUES (436,'Geoffrey Rush','P.O. Box 118, 7829 Arcu Rd.');
INSERT INTO customer (c_id,name,address) VALUES (437,'Nehru Velasquez','1855 Ligula. Rd.');
INSERT INTO customer (c_id,name,address) VALUES (438,'Jasper Olsen','P.O. Box 997, 2078 Ultrices, Avenue');
INSERT INTO customer (c_id,name,address) VALUES (439,'Clinton Mack','P.O. Box 223, 5896 Proin Av.');
INSERT INTO customer (c_id,name,address) VALUES (440,'Reese Baldwin','514-7852 Proin Avenue');
INSERT INTO customer (c_id,name,address) VALUES (441,'Keith Dyer','Ap #625-3828 Lorem Avenue');
INSERT INTO customer (c_id,name,address) VALUES (442,'Samuel Torres','Ap #315-9321 Aliquam Rd.');
INSERT INTO customer (c_id,name,address) VALUES (443,'Orlando Travis','Ap #501-5345 Venenatis St.');
INSERT INTO customer (c_id,name,address) VALUES (444,'Aladdin Henderson','P.O. Box 576, 9512 Mi, Ave');
INSERT INTO customer (c_id,name,address) VALUES (445,'Jack Horton','577-3376 Etiam Ave');
INSERT INTO customer (c_id,name,address) VALUES (446,'Phelan Cline','7236 Urna. Rd.');
INSERT INTO customer (c_id,name,address) VALUES (447,'Rudyard Burris','637-5325 Nulla Street');
INSERT INTO customer (c_id,name,address) VALUES (448,'Orson Hutchinson','584-7188 Massa. Avenue');
INSERT INTO customer (c_id,name,address) VALUES (449,'Patrick Bean','664-2094 Eleifend Av.');
INSERT INTO customer (c_id,name,address) VALUES (450,'Deacon Donovan','131-4912 Nunc Avenue');
INSERT INTO customer (c_id,name,address) VALUES (451,'Christian Garner','P.O. Box 130, 4128 Et Ave');
INSERT INTO customer (c_id,name,address) VALUES (452,'Chancellor Haney','7740 Elit, St.');
INSERT INTO customer (c_id,name,address) VALUES (453,'Porter Hood','Ap #358-3794 Sem St.');
INSERT INTO customer (c_id,name,address) VALUES (454,'Arthur West','Ap #431-1748 Malesuada Street');
INSERT INTO customer (c_id,name,address) VALUES (455,'Fritz Sweeney','4618 Ut St.');
INSERT INTO customer (c_id,name,address) VALUES (456,'Brock Best','244 Sed Street');
INSERT INTO customer (c_id,name,address) VALUES (457,'Ian Dalton','P.O. Box 569, 5466 Quisque St.');
INSERT INTO customer (c_id,name,address) VALUES (458,'Bernard Bailey','1796 Cursus Avenue');
INSERT INTO customer (c_id,name,address) VALUES (459,'Benjamin Herman','401-4371 Molestie Road');
INSERT INTO customer (c_id,name,address) VALUES (460,'Samuel Sweeney','Ap #400-6665 Consectetuer Rd.');
INSERT INTO customer (c_id,name,address) VALUES (461,'Erich Collier','Ap #238-3352 Id Av.');
INSERT INTO customer (c_id,name,address) VALUES (462,'Armand Macias','571 Tincidunt Avenue');
INSERT INTO customer (c_id,name,address) VALUES (463,'Abdul York','Ap #501-2385 Donec Road');
INSERT INTO customer (c_id,name,address) VALUES (464,'Yasir Bradford','Ap #817-6948 Sem St.');
INSERT INTO customer (c_id,name,address) VALUES (465,'Theodore Garrison','8454 Dui Street');
INSERT INTO customer (c_id,name,address) VALUES (466,'Gareth Lynn','P.O. Box 842, 2277 In St.');
INSERT INTO customer (c_id,name,address) VALUES (467,'Josiah Knight','259-1414 Duis Street');
INSERT INTO customer (c_id,name,address) VALUES (468,'Chaim Kerr','Ap #344-3233 Arcu Rd.');
INSERT INTO customer (c_id,name,address) VALUES (469,'Marvin Burns','P.O. Box 570, 676 Porttitor St.');
INSERT INTO customer (c_id,name,address) VALUES (470,'Xavier Callahan','P.O. Box 827, 134 Ultrices St.');
INSERT INTO customer (c_id,name,address) VALUES (471,'Declan Benson','Ap #703-5666 Dolor. Ave');
INSERT INTO customer (c_id,name,address) VALUES (472,'Lawrence Mathews','Ap #238-4832 Erat, St.');
INSERT INTO customer (c_id,name,address) VALUES (473,'Ferris Lucas','Ap #414-5837 Suspendisse St.');
INSERT INTO customer (c_id,name,address) VALUES (474,'Jeremy Orr','6900 Scelerisque Road');
INSERT INTO customer (c_id,name,address) VALUES (475,'Quamar Meyer','1364 Faucibus Road');
INSERT INTO customer (c_id,name,address) VALUES (476,'Judah Morrow','732 Parturient Ave');
INSERT INTO customer (c_id,name,address) VALUES (477,'Jelani Oneal','P.O. Box 912, 2601 Convallis Av.');
INSERT INTO customer (c_id,name,address) VALUES (478,'Stuart Salazar','Ap #342-9976 Aliquam St.');
INSERT INTO customer (c_id,name,address) VALUES (479,'Abdul Holman','P.O. Box 926, 4556 Vitae Avenue');
INSERT INTO customer (c_id,name,address) VALUES (480,'Elmo Mccormick','2381 Ultrices. St.');
INSERT INTO customer (c_id,name,address) VALUES (481,'Allen Webb','218-5925 Sodales. St.');
INSERT INTO customer (c_id,name,address) VALUES (482,'Theodore Ramirez','673-1395 Vulputate St.');
INSERT INTO customer (c_id,name,address) VALUES (483,'Boris Burks','Ap #820-1402 A, Av.');
INSERT INTO customer (c_id,name,address) VALUES (484,'Brock Myers','696-9299 Vitae St.');
INSERT INTO customer (c_id,name,address) VALUES (485,'Mannix Walton','P.O. Box 558, 6704 Lectus. Rd.');
INSERT INTO customer (c_id,name,address) VALUES (486,'Hasad Poole','P.O. Box 863, 8243 Aenean St.');
INSERT INTO customer (c_id,name,address) VALUES (487,'Colby Mccray','Ap #480-7581 Sodales Ave');
INSERT INTO customer (c_id,name,address) VALUES (488,'Caesar Estes','Ap #417-636 Suscipit Street');
INSERT INTO customer (c_id,name,address) VALUES (489,'Ishmael Glass','860-1265 Dui, Av.');
INSERT INTO customer (c_id,name,address) VALUES (490,'Lucian Hess','Ap #135-3968 Sapien, Ave');
INSERT INTO customer (c_id,name,address) VALUES (491,'Eric Mercado','925-2447 Aliquam St.');
INSERT INTO customer (c_id,name,address) VALUES (492,'Aidan Curry','Ap #453-4966 Lorem Street');
INSERT INTO customer (c_id,name,address) VALUES (493,'Palmer Morin','Ap #959-1358 Ut, Av.');
INSERT INTO customer (c_id,name,address) VALUES (494,'Phelan Garrison','8447 Et Road');
INSERT INTO customer (c_id,name,address) VALUES (495,'Cade Dyer','Ap #719-2172 Eu Rd.');
INSERT INTO customer (c_id,name,address) VALUES (496,'Dolan Hinton','836-1546 Ipsum Street');
INSERT INTO customer (c_id,name,address) VALUES (497,'Daquan Kaufman','P.O. Box 418, 9893 Nulla Road');
INSERT INTO customer (c_id,name,address) VALUES (498,'Chester Steele','Ap #310-8087 Laoreet Road');
INSERT INTO customer (c_id,name,address) VALUES (499,'Otto Berger','614 Nam Avenue');
INSERT INTO customer (c_id,name,address) VALUES (500,'Emerson Ortega','7872 Lorem Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (501,'TaShya Tyler','944-3102 Tellus Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (502,'Sonia Tran','143-935 Ultrices Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (503,'Hanna Browning','2537 Ut, Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (504,'Rinah Simpson','P.O. Box 772, 174 Lacus. St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (505,'Suki Barker','Ap #364-1165 Ut, Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (506,'Claudia Sloan','8178 Elit Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (507,'Karleigh Reid','147-3404 Fringilla Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (508,'Sarah Battle','P.O. Box 537, 4241 A, St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (509,'Shana Valenzuela','Ap #817-3260 Lorem St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (510,'Imani Mccray','P.O. Box 843, 5147 Lacinia Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (511,'Tatum Charles','728-3003 Aenean Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (512,'Debra Dodson','6845 Nullam Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (513,'Samantha Whitehead','P.O. Box 366, 5699 Conubia Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (514,'Mariam Rojas','Ap #976-5737 Tortor Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (515,'Priscilla Donovan','908-6725 Tristique Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (516,'Kendall Strong','P.O. Box 590, 4302 Rutrum Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (517,'Clementine Turner','Ap #869-5604 Pretium Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (518,'Bryar Reynolds','831-1283 Lorem Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (519,'Kaitlin Wilcox','684-5971 Vestibulum Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (520,'Marah Evans','P.O. Box 312, 9797 Turpis. Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (521,'Stacy Riddle','Ap #910-6534 Malesuada. Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (522,'Robin Oneill','544-3751 Quam, St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (523,'Isadora Dunlap','2674 Vulputate Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (524,'Adria Wise','Ap #996-7682 Sed Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (525,'Jana Warren','524-6892 Dui. Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (526,'Maryam Morton','P.O. Box 829, 7092 Tempus Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (527,'Natalie Grant','826-9387 Arcu. Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (528,'Patricia Shaffer','269 Odio. Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (529,'Shelley Avery','106-8424 Ultrices Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (530,'Alexandra Garrison','1896 Varius. Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (531,'Kimberley Britt','6036 Ante. Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (532,'Frances Park','P.O. Box 771, 1752 Nascetur St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (533,'Sylvia Dorsey','P.O. Box 205, 5042 Non Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (534,'Daria Carter','7766 Pede St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (535,'Kimberley Rosario','P.O. Box 411, 1132 Nisi. Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (536,'Christen Bullock','P.O. Box 889, 2337 In Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (537,'Sydney Hunt','P.O. Box 210, 4443 Dictum Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (538,'Carla Noel','4900 Est, Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (539,'Chava Britt','P.O. Box 418, 5950 Nibh. Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (540,'Jaquelyn Rodriguez','2236 Vestibulum Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (541,'Vielka Berger','Ap #689-6037 Aliquam Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (542,'Rhonda Holloway','2504 Vitae Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (543,'Chiquita Scott','249 Nec St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (544,'Heather Olson','973-1400 Mauris Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (545,'Liberty Terry','304-6954 In Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (546,'Miriam Dejesus','P.O. Box 961, 4053 Id, Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (547,'Isabella Cooke','Ap #262-2982 Proin Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (548,'Kylynn Conley','390 Ac St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (549,'Cora Finley','6842 Nec Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (550,'Simone Stark','234-8302 Posuere Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (551,'Josephine Benson','630-6087 Morbi Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (552,'Libby Tyson','P.O. Box 930, 4606 Ac St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (553,'Quin Nichols','P.O. Box 121, 5156 Sit Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (554,'Jolie Ochoa','656-2360 Vivamus St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (555,'Amity Deleon','374-1736 Malesuada Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (556,'Dora Hernandez','P.O. Box 498, 3906 Mi St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (557,'Kathleen Farrell','Ap #486-2326 Non, Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (558,'Angelica Hood','9499 Et, Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (559,'Lacota Franks','1235 Aliquam, Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (560,'Ifeoma Gallagher','P.O. Box 682, 1624 Cras Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (561,'Echo Harrell','701-9520 Mauris Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (562,'Octavia Clayton','689-6612 Vitae Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (563,'Hedwig Whitfield','554-177 Elit, Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (564,'Dominique Chan','P.O. Box 123, 6614 Rhoncus. Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (565,'Alana Robbins','P.O. Box 996, 2572 Aliquam Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (566,'Victoria Lloyd','8258 Sit Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (567,'Ori Mccray','Ap #286-687 Enim. Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (568,'Kay Petersen','P.O. Box 286, 793 Metus Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (569,'Barbara Fields','450-2927 Vel Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (570,'Desiree Finley','545-5216 Dui. Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (571,'Macey Eaton','835 Id Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (572,'Nina Abbott','5448 Rutrum St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (573,'Iola Ramirez','P.O. Box 198, 7406 Non Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (574,'Haley Lane','840-9338 Sociosqu Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (575,'Clementine Summers','Ap #687-9540 Dignissim Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (576,'Cara Marquez','Ap #640-4981 Mauris St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (577,'Flavia Hunter','Ap #956-5703 Ullamcorper Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (578,'Cameron Howard','Ap #999-2725 Vestibulum Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (579,'Ramona Underwood','2560 Vel Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (580,'Serina Crawford','P.O. Box 815, 2911 Risus Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (581,'Wendy Riddle','743-6134 At St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (582,'Debra Golden','857-2160 Dolor. St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (583,'Cameron Morris','5973 Tempor Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (584,'Nyssa Mendez','P.O. Box 695, 3656 Sagittis Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (585,'Kiona Acevedo','914 Duis Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (586,'Imelda Wolfe','P.O. Box 943, 8743 Lobortis Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (587,'Joan Dudley','794-168 Lectus Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (588,'Glenna Wall','P.O. Box 421, 4985 Odio Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (589,'Orli Serrano','1920 Lobortis, St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (590,'Nita Boone','4266 Elementum Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (591,'Tatiana Jordan','203 Netus Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (592,'Selma Wright','Ap #891-4514 Blandit Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (593,'Carol Fuller','P.O. Box 548, 2608 Dapibus Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (594,'Lani Douglas','8263 Mauris Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (595,'Brenna Robinson','P.O. Box 642, 6178 Enim, Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (596,'Alana Cantrell','P.O. Box 439, 6565 Enim. Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (597,'Meredith Rhodes','P.O. Box 711, 6317 Eu Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (598,'Kimberly Hardy','5244 Eu, Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (599,'Macey Hammond','Ap #444-1771 Cras St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (600,'Jocelyn Webb','240 Phasellus St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (601,'Yuri Herrera','973-7890 Non, Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (602,'Avye Hines','P.O. Box 946, 238 Donec St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (603,'Maggy Swanson','778-5718 Felis St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (604,'Blair Church','3508 Nulla Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (605,'Kendall Blanchard','P.O. Box 769, 4224 Felis Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (606,'Madaline Wilcox','P.O. Box 442, 9158 Ipsum Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (607,'Galena Patterson','7884 Consectetuer Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (608,'Justine Joyce','P.O. Box 978, 7009 Gravida Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (609,'Ori Knox','811-9195 Nec, Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (610,'Jeanette Crane','Ap #657-6764 Imperdiet, St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (611,'Wendy Mclean','297-2562 Augue Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (612,'Hiroko Dorsey','Ap #745-2244 Nulla. Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (613,'Jena Goff','P.O. Box 272, 9895 In, St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (614,'Athena Richards','881-2668 Hendrerit Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (615,'Lael Hall','9244 Mauris Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (616,'Vivien Fitzpatrick','Ap #687-5691 Facilisis Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (617,'Alisa Mccormick','P.O. Box 165, 7896 Et St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (618,'Galena Michael','122-3261 Ligula Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (619,'Whitney Bailey','648-1419 At, Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (620,'Madison Rhodes','587-3119 A Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (621,'Tanya Jenkins','Ap #613-1095 Proin Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (622,'Georgia Wallace','Ap #283-7584 Eleifend Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (623,'Brittany Gutierrez','828-6974 Imperdiet Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (624,'Nelle Evans','Ap #275-756 Neque. Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (625,'Vielka Romero','P.O. Box 787, 2565 Ligula Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (626,'Xandra Hinton','859-5987 Proin Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (627,'Lacey Holder','P.O. Box 205, 8126 Massa Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (628,'Penelope Matthews','359-3130 Tincidunt Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (629,'Miranda Weeks','Ap #616-2956 Fusce Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (630,'Callie Workman','400-2528 Auctor Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (631,'Tatyana Mitchell','Ap #140-1432 A Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (632,'Bertha Daugherty','P.O. Box 961, 6907 Nostra, St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (633,'Daryl Chase','P.O. Box 973, 6602 Et, Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (634,'Kalia Sims','266-6542 Integer St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (635,'Rinah Gross','621-8442 Sociis St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (636,'Laurel Munoz','639-248 Eget Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (637,'Ella Gregory','P.O. Box 132, 8973 A, Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (638,'Blair Bauer','4125 Vivamus Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (639,'Brenda Garrison','Ap #791-1495 Malesuada Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (640,'Paloma Larsen','Ap #577-9259 Egestas. St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (641,'Signe Odom','Ap #926-2799 Tempor Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (642,'Halee Velasquez','294-6049 Luctus Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (643,'Zephr Henry','7110 Donec Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (644,'Leslie Hood','P.O. Box 668, 3016 Feugiat Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (645,'Camille Buchanan','5801 Sit Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (646,'Illana Kirby','704-7905 Vulputate Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (647,'Dominique Keith','P.O. Box 647, 159 Duis Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (648,'Vanna Holt','P.O. Box 240, 7939 Augue St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (649,'Summer Taylor','7546 Tellus Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (650,'Penelope Lynn','P.O. Box 717, 1631 Interdum Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (651,'Whitney Donovan','P.O. Box 774, 3168 Aliquam Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (652,'Geraldine Alexander','466-3203 Ac Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (653,'Bertha Blevins','377-7489 Sem, Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (654,'Hyacinth Strickland','840-1097 Neque Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (655,'Chastity Murphy','P.O. Box 166, 221 Magna Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (656,'Leah Rowe','Ap #517-1825 Sit Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (657,'Keely Shannon','Ap #424-9257 Viverra. Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (658,'Ria Walton','P.O. Box 692, 7224 In Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (659,'Evelyn Roman','Ap #354-9845 Tellus Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (660,'Clio Sweet','408-2584 Tempor St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (661,'Xandra Whitehead','P.O. Box 977, 3475 Metus. Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (662,'Venus Simon','P.O. Box 478, 5538 Orci, Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (663,'Delilah Fields','Ap #620-9525 Mauris Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (664,'Casey Mcleod','P.O. Box 485, 2355 Enim, St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (665,'Kirsten Zamora','P.O. Box 349, 3027 In Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (666,'Hilda Hale','Ap #688-9197 Non Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (667,'Darryl Taylor','5743 In Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (668,'Catherine Lambert','Ap #634-190 Dui. Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (669,'Vivien Coffey','Ap #419-7291 Felis St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (670,'Ila Moody','460-3559 Duis Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (671,'Halee Singleton','P.O. Box 112, 5697 Ut, Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (672,'Isabella Goodman','P.O. Box 825, 1505 Risus Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (673,'Tallulah Estrada','566-3084 Montes, St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (674,'Portia Hewitt','397-9062 Et, Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (675,'Xerxes Riggs','Ap #915-5162 Nonummy Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (676,'Fleur Montoya','Ap #372-7904 Malesuada St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (677,'Blair Sosa','309-947 Sed St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (678,'Britanni Valencia','5032 Semper. St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (679,'Sloane Charles','Ap #673-1232 Tellus St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (680,'Amber Cooke','269-264 Adipiscing, Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (681,'Yen Lindsay','341-7930 Ut St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (682,'Sylvia Snider','Ap #413-3468 Magna. Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (683,'Susan Wells','5810 Feugiat Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (684,'Pascale Nolan','Ap #255-1567 Nulla. Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (685,'Kylynn Knight','513-3490 Mus. Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (686,'Rae Weeks','686-3169 Dictum St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (687,'Cassandra Browning','Ap #799-6972 Vel Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (688,'Renee Anderson','924-1204 Ipsum. Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (689,'Marcia Dunn','Ap #211-5164 Vestibulum, Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (690,'Miriam Day','313-3689 Vitae Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (691,'Jane Bentley','4246 Nibh. Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (692,'Charissa Weiss','8020 Orci, Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (693,'Meredith Rosales','2679 Purus. St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (694,'Regan Rivers','P.O. Box 332, 6869 Id Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (695,'Zia Cannon','8108 Tortor. Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (696,'Quyn Bernard','440-8902 Ullamcorper Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (697,'Sharon Hayden','4279 At Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (698,'Chiquita Burton','204-7846 Urna. Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (699,'Madaline Mejia','611-4000 Litora Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (700,'Celeste Cabrera','6147 Non Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (701,'Unity Mcgowan','P.O. Box 239, 6631 Sagittis Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (702,'Megan Roth','P.O. Box 943, 1867 Posuere Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (703,'Joy Garcia','401 Arcu. Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (704,'Alexis Hancock','P.O. Box 544, 1653 Purus. Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (705,'Jade Wright','P.O. Box 605, 4862 Non Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (706,'Lacy Merrill','8781 Per Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (707,'Summer Leblanc','238-3422 Libero Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (708,'Lavinia Parks','269-5698 Lacus. Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (709,'Libby Wilkerson','7873 Eu, Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (710,'Georgia Marks','Ap #625-6163 Dui Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (711,'Avye Gonzalez','P.O. Box 809, 5456 Ornare, Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (712,'Helen Justice','Ap #711-6256 Tortor, Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (713,'Amelia Crane','790-2305 Sed Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (714,'Linda Cohen','P.O. Box 928, 1380 Ut Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (715,'Anastasia Roth','Ap #572-3721 Facilisis Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (716,'Aiko Potts','5814 Rutrum Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (717,'Aspen Stout','2397 Libero. Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (718,'Cara Powell','P.O. Box 267, 6504 Eu Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (719,'Ignacia Whitney','193-7042 Venenatis Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (720,'Riley Bullock','132-9907 Consequat Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (721,'Leslie Vega','Ap #815-2161 Sapien, Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (722,'Kitra Woods','717-8532 Risus Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (723,'Mari Salazar','P.O. Box 550, 959 Nulla St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (724,'Cheyenne Daniels','P.O. Box 373, 7143 Mi Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (725,'Ariel Lowery','P.O. Box 941, 3907 Pede Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (726,'Guinevere Rivas','Ap #559-9520 Lorem Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (727,'Diana Gamble','3747 Purus, Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (728,'Emily Mcleod','Ap #828-3785 Felis St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (729,'Lani Mcmillan','Ap #354-6032 Aliquam St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (730,'Ava Howell','5091 Aliquam, Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (731,'Dawn Aguirre','250-6997 Euismod St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (732,'Blair Velasquez','Ap #238-2253 Purus St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (733,'Rhoda Shepard','P.O. Box 766, 6214 Euismod Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (734,'Tatum Silva','498-5815 Ac St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (735,'Haley Robbins','639 Eu St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (736,'Amethyst Dunn','Ap #623-8573 Erat Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (737,'Ila Spence','Ap #304-2323 Odio, Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (738,'Mikayla Dillon','170-6349 Arcu St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (739,'Cameran Oconnor','Ap #258-4349 Egestas St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (740,'Brynne Gamble','Ap #480-5648 In, St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (741,'Renee Mcgowan','Ap #456-8753 Mauris Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (742,'Keiko Robertson','P.O. Box 392, 2950 Lorem Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (743,'Cecilia Henson','120-739 Nec Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (744,'Marny Barton','P.O. Box 555, 6655 Ultrices Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (745,'Carla Wilder','Ap #172-1793 Sem, Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (746,'Sharon Stone','798-1195 Ipsum Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (747,'Kameko Wilson','Ap #335-7396 Pede. St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (748,'Frances Cameron','P.O. Box 961, 7288 A, Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (749,'Brynne Vaughn','1779 At, Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (750,'Buffy Campbell','176-2251 Ac Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (751,'Quintessa Hester','192-5710 Ornare, Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (752,'Azalia Herman','P.O. Box 504, 1605 Sed Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (753,'Buffy Noel','Ap #560-6300 Rhoncus. Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (754,'Cheryl Cunningham','7054 Orci Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (755,'Isabella Bass','887-4870 Turpis Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (756,'Naida Chambers','Ap #185-8193 Elementum Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (757,'Aileen Rose','Ap #853-2705 Morbi Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (758,'Maggie Mcknight','P.O. Box 651, 6645 Sit Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (759,'Hedda Norman','465-168 Lobortis Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (760,'Shaeleigh Mcdaniel','P.O. Box 716, 4124 Sociis Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (761,'Kameko Schmidt','7522 Elit. St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (762,'Xaviera Whitney','P.O. Box 597, 9443 Integer Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (763,'Cassady Nichols','Ap #606-4570 Nunc St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (764,'Roary Foster','2954 A St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (765,'Rhea Hogan','P.O. Box 793, 6046 Blandit. Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (766,'Freya Heath','Ap #112-8467 Dignissim Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (767,'Jana Cash','P.O. Box 350, 704 Pharetra. Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (768,'Farrah David','7574 Cum Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (769,'Bree Barber','7113 Erat Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (770,'Colleen Chaney','P.O. Box 167, 2410 Auctor Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (771,'Minerva Clayton','P.O. Box 256, 4201 Vestibulum. Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (772,'Madaline Ayala','P.O. Box 565, 1254 Odio St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (773,'Sandra Miranda','Ap #656-2101 Ante. Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (774,'Paloma Lang','Ap #974-269 Mi. St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (775,'Dora Ellison','8342 Primis Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (776,'Kitra Ortega','6360 Tristique St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (777,'Hanna Drake','788-9772 Dictum Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (778,'Dominique Pugh','6984 Praesent Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (779,'Lacota Holmes','P.O. Box 761, 619 In Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (780,'Renee Fowler','998-349 Dolor Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (781,'Linda Norris','P.O. Box 304, 2186 Ligula. Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (782,'Sybill Michael','159-4695 Lacus St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (783,'Briar Young','985-8814 Eu Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (784,'Jacqueline Snyder','Ap #100-4579 Commodo Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (785,'Jade Hess','Ap #481-1761 Feugiat. St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (786,'Marny Hinton','Ap #857-1766 Vitae Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (787,'Jeanette Mcintyre','Ap #588-5241 Nec Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (788,'Kristen Vega','4145 Sociis Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (789,'Uma Mclean','1843 Gravida St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (790,'Irene Gallegos','445-2374 Turpis. St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (791,'Harriet Forbes','Ap #737-4061 Commodo Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (792,'Hillary Moody','711-1782 Pharetra Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (793,'Kaitlin Mckenzie','124-5178 Pede St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (794,'Zephr Williams','Ap #181-418 Cursus Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (795,'Teegan Marquez','890-5979 Libero. Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (796,'Eden Wallace','P.O. Box 602, 4604 Velit Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (797,'Kylie Vang','9939 Purus St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (798,'Cheryl Sargent','4796 Enim. Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (799,'Illana Harmon','7636 Nunc Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (800,'Marah Stuart','Ap #866-3344 Lobortis Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (801,'Emerald Carver','P.O. Box 656, 1354 Vitae, Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (802,'Uma Holder','304-4127 Turpis Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (803,'Illana Schultz','432-361 Fusce St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (804,'Rhona Tucker','5342 Proin St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (805,'Hadassah Burns','P.O. Box 590, 2049 Enim Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (806,'Pamela Schneider','Ap #426-6098 Curae; Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (807,'Jane Marquez','4875 Mauris Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (808,'Tamekah Hickman','P.O. Box 507, 5096 Neque. Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (809,'Jenna Simmons','152-8994 Amet Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (810,'Guinevere Mcdaniel','Ap #620-3855 Dapibus Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (811,'Orla Mercado','P.O. Box 120, 5776 Nam Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (812,'Maisie Grimes','P.O. Box 635, 4785 Odio. Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (813,'Rosalyn Swanson','Ap #891-5965 Vitae Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (814,'Taylor Rodriquez','Ap #647-5432 Erat Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (815,'Mallory Riley','5160 Tempor Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (816,'Sydnee Rogers','874-7748 Lorem. Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (817,'Shaeleigh Cole','313-1334 Adipiscing Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (818,'Suki Puckett','P.O. Box 168, 2371 Urna Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (819,'Imani Dominguez','2825 Euismod Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (820,'Lysandra Duke','591-8364 Duis Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (821,'Shaine Holmes','P.O. Box 982, 4913 Egestas. Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (822,'Kylie Duncan','Ap #657-7694 Enim. Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (823,'Raven Odom','P.O. Box 439, 8993 Metus Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (824,'Brynn Tillman','307-9576 Cursus Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (825,'Bell Holmes','Ap #677-2657 Metus. St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (826,'Clare Warner','P.O. Box 623, 6830 Nulla. Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (827,'Moana Daugherty','345-9976 Arcu Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (828,'Susan Daniel','596 Cum Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (829,'Elaine Travis','P.O. Box 762, 8534 Dictum Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (830,'Ginger Roy','Ap #250-2915 Aliquam Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (831,'Kaitlin Lawson','9120 Iaculis, Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (832,'Neve Mason','5692 Ridiculus Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (833,'Phyllis English','Ap #410-4091 In Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (834,'Brynne Cervantes','705-6122 Nam St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (835,'Hanna Briggs','Ap #750-5569 Nunc Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (836,'Nicole Castro','Ap #769-6569 Ornare Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (837,'Hadley Collier','342 Malesuada Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (838,'Ruth Mcdowell','881-1437 In St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (839,'Claudia Lyons','Ap #429-9557 Lectus Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (840,'Kiona Foreman','229-4360 Aliquam Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (841,'Aubrey Hutchinson','3550 Eu, Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (842,'Keelie Holloway','Ap #904-1179 Luctus Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (843,'Clio Rosales','471-709 Euismod St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (844,'Libby Santiago','7336 Ac Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (845,'Miranda Salazar','695-7007 Magna. Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (846,'Odette Mccall','277-7840 Massa. Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (847,'Veda Scott','621-2535 Non, Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (848,'Sonya Maxwell','Ap #521-8958 Sem, Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (849,'Ursula Clark','P.O. Box 968, 4348 Aliquet Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (850,'Uma Fowler','Ap #692-5596 Ac Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (851,'Jamalia Andrews','P.O. Box 665, 5063 Libero Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (852,'Aiko Fox','2342 Tellus Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (853,'Kaye Holder','P.O. Box 765, 3673 Erat. Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (854,'Mia Valencia','843-9487 Quam St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (855,'Darryl Parsons','768-6085 Pharetra Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (856,'Isabella Cotton','P.O. Box 847, 6747 Iaculis Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (857,'Candice Burton','Ap #218-7215 Duis Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (858,'Sheila Roth','404 Gravida Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (859,'Zenaida Roberson','738-164 Fringilla St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (860,'Wynne Gonzales','P.O. Box 602, 8417 Porttitor Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (861,'Joan Erickson','P.O. Box 826, 7426 Aenean Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (862,'Nicole Klein','959 Aptent Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (863,'Sandra Sanchez','Ap #213-4193 Ut St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (864,'Olympia Cole','790-1207 Phasellus Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (865,'Angelica Miles','631-4252 Suspendisse Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (866,'Beverly Rivers','1898 Metus. Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (867,'Candace Alvarez','826-1240 Molestie Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (868,'Glenna Ochoa','P.O. Box 717, 2062 Maecenas Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (869,'Penelope Hernandez','P.O. Box 273, 1629 Sem. Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (870,'Rhoda Fitzpatrick','7802 Vitae Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (871,'Wyoming Collins','604-398 Commodo Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (872,'Clare Morales','2478 Class Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (873,'Maite Johnston','934-2262 Amet Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (874,'Clio Rowland','763-367 A, Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (875,'Abra Sutton','Ap #880-904 Erat, Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (876,'Kessie Raymond','489-5065 Dui. Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (877,'Velma Sellers','Ap #882-1669 Leo. St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (878,'Rama Higgins','Ap #798-365 Sed Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (879,'Mona Woodard','5490 Tristique Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (880,'Bo Robinson','Ap #984-7966 Morbi St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (881,'Portia Humphrey','6031 Mattis Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (882,'Azalia Meadows','Ap #533-4671 Hymenaeos. St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (883,'Nora Stephenson','Ap #722-1207 Magna, Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (884,'Hope Allen','3555 Enim, Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (885,'Mona Wilson','Ap #768-2822 Sed Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (886,'Rhona Curtis','920-8991 Cursus Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (887,'Farrah Montgomery','977-7846 Ac Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (888,'Kylan Cotton','7498 Aenean Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (889,'Serina Joyner','597-4405 Nullam Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (890,'Neve Burton','Ap #169-7896 Fusce St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (891,'Kameko Flores','P.O. Box 500, 1983 Dolor Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (892,'Camilla Snyder','6833 Turpis Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (893,'Latifah Sharpe','1429 Sagittis Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (894,'Lavinia Ryan','637-5673 Dapibus St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (895,'Sandra Wilkins','Ap #928-1648 Feugiat. Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (896,'Tamekah Farmer','920-6936 Vivamus Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (897,'Ginger Orr','Ap #950-5996 Elit, Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (898,'Shaine Nguyen','9757 Nunc St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (899,'Nina Mcmillan','891-9149 Lectus Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (900,'Evelyn Ellison','Ap #554-3415 Dolor, Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (901,'Shelley French','416-5951 Nascetur Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (902,'Kiayada Nunez','P.O. Box 101, 9635 Sed St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (903,'Eleanor Leblanc','P.O. Box 467, 7701 Suspendisse Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (904,'Kaden Levine','686-506 Tristique Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (905,'Rina Stafford','Ap #134-6023 Mauris Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (906,'Jillian Hickman','Ap #875-8732 In Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (907,'Hilary Campbell','P.O. Box 879, 7249 At Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (908,'Leigh Hughes','Ap #270-9735 Bibendum Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (909,'Orli Goodman','5734 Purus Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (910,'Clementine Ray','448-6451 Ultrices. St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (911,'Pearl Justice','Ap #462-1224 Sit Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (912,'Basia Butler','Ap #463-2278 Quis Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (913,'Quin Gonzalez','Ap #247-9714 Metus. Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (914,'Sybill Townsend','P.O. Box 552, 7972 Sodales. Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (915,'Fatima Scott','P.O. Box 120, 2115 Pellentesque. Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (916,'Veronica Faulkner','972-1038 Erat Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (917,'Sonia Goodman','Ap #433-6130 Et Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (918,'Barbara Brennan','8370 Euismod Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (919,'Charde Soto','120-930 Eros Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (920,'Lacota Carrillo','859-2777 Suspendisse Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (921,'Sybil Shaffer','3731 Varius. Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (922,'Rhoda Mcintosh','8030 Vitae Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (923,'Joan Carey','450-2025 Ullamcorper. Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (924,'Yoko Petty','P.O. Box 346, 8323 Elit, Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (925,'Amethyst Mcfarland','925-546 Per St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (926,'Lois Monroe','3530 Sagittis Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (927,'Rhiannon Jarvis','P.O. Box 968, 7102 Mi Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (928,'Quynn Wilcox','197 Pede Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (929,'Angela Fox','P.O. Box 891, 9723 Rhoncus. Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (930,'Yetta Leon','453-7188 Ultricies Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (931,'Hadassah Watkins','P.O. Box 609, 3859 Adipiscing Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (932,'Grace Fitzpatrick','4373 Curabitur Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (933,'Cassidy Delaney','Ap #236-6041 Sit Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (934,'Fleur Frost','Ap #557-8260 Sociis Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (935,'Madeline Sandoval','7002 Vestibulum Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (936,'Cheyenne Francis','4856 Sit St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (937,'Allegra Russo','Ap #586-5670 Mauris St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (938,'Maggy Atkins','P.O. Box 504, 7653 Metus. Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (939,'Montana Hinton','142 Scelerisque St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (940,'Octavia Rodriguez','P.O. Box 406, 5495 Nunc Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (941,'Dominique Cleveland','9709 Natoque Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (942,'Orla Baldwin','9782 Scelerisque St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (943,'Angela Lynch','5544 Odio Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (944,'Kylie Adams','Ap #198-2562 Purus St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (945,'Wynter Johnston','Ap #986-2101 Consequat Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (946,'Maris Gilbert','P.O. Box 984, 955 Cras Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (947,'Cheryl Trevino','P.O. Box 681, 8122 Donec Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (948,'Kellie Mcdaniel','1503 Eu Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (949,'Joelle Harvey','Ap #657-4908 Elit. St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (950,'Yael Finley','404-1610 Lobortis St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (951,'Sacha Dorsey','785-1329 Lectus. Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (952,'Sara Lancaster','7344 Morbi Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (953,'Reagan Hudson','Ap #680-3758 Facilisis. Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (954,'Rebecca Nicholson','4657 Quisque St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (955,'Maris Alexander','415 Aliquam Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (956,'Oprah English','841-6110 Gravida Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (957,'Ursa Ayala','167-3386 Magna. Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (958,'Nyssa Lucas','Ap #625-832 Proin Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (959,'Imani Burgess','7047 Convallis Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (960,'Dana Dean','922-1242 Augue, Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (961,'Cheyenne Pugh','584-397 Aliquet St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (962,'Sara Greer','Ap #720-3827 Accumsan Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (963,'Sylvia Rowland','403-8836 Mauris Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (964,'Hedwig Curry','3132 Odio St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (965,'Nicole Merrill','1284 Dolor Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (966,'Alika Mendoza','2873 Suspendisse Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (967,'Dawn Cantu','P.O. Box 160, 5962 Metus Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (968,'Charde Whitaker','Ap #869-3828 Auctor Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (969,'Olivia Howard','178-5851 Vulputate Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (970,'Simone Rocha','P.O. Box 191, 8366 Facilisis Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (971,'Isabella Rodgers','P.O. Box 949, 3895 Luctus Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (972,'Paloma Mckinney','P.O. Box 582, 7359 Sit Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (973,'Tallulah Maynard','P.O. Box 751, 9777 Iaculis St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (974,'Angela Zamora','863 Vulputate, Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (975,'Fiona Greene','Ap #773-5862 Faucibus Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (976,'Sandra Fuller','P.O. Box 432, 9575 Malesuada Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (977,'Maya Skinner','Ap #811-2826 Consectetuer St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (978,'Aimee Clemons','5644 Diam St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (979,'Irma Park','913-9708 Lorem Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (980,'Hanae Arnold','Ap #305-1552 Sit Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (981,'Marny Cruz','5751 Nec St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (982,'Audrey Carson','P.O. Box 809, 1649 Velit Av.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (983,'Maisie Spencer','P.O. Box 516, 5731 Feugiat Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (984,'Mary Davidson','3486 Lectus St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (985,'Sonia Carver','193-2658 Placerat, St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (986,'Carolyn Ferrell','P.O. Box 284, 8988 Orci Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (987,'Portia Potter','605-6838 Mauris Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (988,'Meredith Christian','Ap #316-5153 Tincidunt, Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (989,'Audra Sargent','P.O. Box 582, 380 Consectetuer, Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (990,'Rinah Mccall','8304 Turpis Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (991,'Jasmine Estes','8987 Viverra. Avenue');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (992,'Daryl Wilson','9193 Ligula Street');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (993,'Veda Landry','Ap #641-3669 Varius Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (994,'Cora Cohen','408-7460 Gravida St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (995,'Nita Townsend','P.O. Box 138, 6852 Nisl Road');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (996,'India Fulton','Ap #215-3747 Dui. Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (997,'Violet Reynolds','480-7516 Aliquam Ave');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (998,'Noelani Maddox','833-7871 Eu Rd.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (999,'Keelie Pearson','P.O. Box 316, 5759 Euismod St.');
INSERT INTO CUSTOMER (c_id,name,address) VALUES (1000,'Justina Garrett','247-3760 Et Ave');